Repository twosigma/Cook, pull requests merged in 2018-03, with the labels that each got.

#745 cs: refactor: sorts config.edn
  scheduler/config.edn
Labels: refactoring

#750 Fixes support for cs cat on a binary file
  cli/cook/mesos.py
  cli/cook/subcommands/cat.py
  cli/cook/version.py
  integration/tests/cook/test_cli.py
Labels: bug, cli

#741 Adds mount minimally
  scheduler/project.clj
  scheduler/src/cook/components.clj
  scheduler/src/cook/config.clj
  scheduler/src/cook/datomic.clj
  scheduler/src/cook/mesos.clj
  scheduler/src/cook/mesos/monitor.clj
  scheduler/test/cook/test/config.clj
  scheduler/test/cook/test/mesos/monitor.clj
  scheduler/test/cook/test/testutil.clj
Labels: refactoring

#757 Adds deeper integration with mount
  scheduler/src/cook/components.clj
  scheduler/src/cook/config.clj
  scheduler/src/cook/mesos.clj
  scheduler/src/cook/mesos/scheduler.clj
  scheduler/src/cook/mesos/task.clj
  scheduler/test/cook/test/mesos/scheduler.clj
  scheduler/test/cook/test/mesos/task.clj
  scheduler/test/cook/test/simulator.clj
Labels: refactoring

#761 Outgoing/caching2
  scheduler/src/cook/mesos/util.clj
Labels: enhancement

#762 Use d/squuid to derive task ID's do that they're more tightly clustered.
  scheduler/src/cook/mesos/scheduler.clj
Labels: enhancement

#763 Change JVM options. remove MaxPermSize and add +UseStringDeduplication
  scheduler/project.clj
Labels: enhancement

#756 Adds support for including custom executor jobs in /jobs
  executor/tests/test_subprocess.py
  scheduler/src/cook/mesos/api.clj
  scheduler/src/cook/mesos/util.clj
  scheduler/test/cook/test/mesos/api.clj
  scheduler/test/cook/test/mesos/util.clj
Labels: enhancement

#775 Fixes bug with single-state /jobs requests
  integration/tests/cook/test_basic.py
  integration/tests/cook/util.py
  scheduler/src/cook/mesos/api.clj
Labels: bug

#774 Includes jobs with a custom executor in cs jobs
  cli/cook/subcommands/jobs.py
  cli/cook/version.py
  integration/tests/cook/test_cli.py
Labels: cli, enhancement
