Repository twosigma/Cook, pull requests merged in 2018-10, with the labels that each got.

#979 Adds pool to task throughput metrics
  scheduler/src/cook/mesos/scheduler.clj
Labels: enhancement, metrics, pools

#993 Allows filtering by pool for cs jobs
  cli/cook/subcommands/jobs.py
  cli/cook/version.py
  integration/tests/cook/cli.py
  integration/tests/cook/test_cli.py
  integration/tests/cook/util.py
Labels: cli, enhancement, pools

#994 Use x-cook-pool header when no pool param is provided
  integration/tests/cook/test_basic.py
  integration/tests/cook/util.py
  scheduler/config.edn
  scheduler/src/cook/mesos/api.clj
Labels: pools

#997 Adds support to cs for submitting docker jobs
  cli/cook/subcommands/submit.py
  cli/cook/version.py
  integration/tests/cook/test_cli.py
Labels: cli, enhancement

#1000 clarifies contents of variable by renaming from pool to pool-name
  scheduler/src/cook/components.clj
  scheduler/src/cook/mesos.clj
  scheduler/src/cook/mesos/monitor.clj
  scheduler/src/cook/mesos/rebalancer.clj
  scheduler/src/cook/mesos/scheduler.clj
  scheduler/src/cook/mesos/util.clj
  scheduler/test/cook/test/mesos/scheduler.clj
  scheduler/test/cook/test/simulator.clj
Labels: refactoring
