Repository twosigma/Cook, pull requests merged in 2019-12, with the labels that each got.

#1322 Prevents errors in launch-tasks from one compute cluster affecting others
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: internal-green, k8s

#1324 Make our compute cluster code more robust between compute clusters.
  scheduler/src/cook/compute_cluster.clj
  scheduler/src/cook/mesos.clj
  scheduler/src/cook/mesos/mesos_compute_cluster.clj
  scheduler/src/cook/rebalancer.clj
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green

#1323 improves time to build user->quota-fn by aggregating queries
  scheduler/src/cook/quota.clj
Labels: internal-green, refactoring

#1329 Bumps CLI version to 2.15.0
  cli/cook/version.py
Labels: cli, internal-green

#1330 Makes test_list_jobs_by_pool complete faster
  integration/tests/cook/test_basic.py
Labels: internal-green, performance, pools, test

#1331 Makes test_progress_update_submit more reliable
  integration/tests/cook/test_basic.py
  integration/tests/cook/util.py
Labels: executor, flaky-test, internal-green, test

#1339 Makes test_progress_update_submit more reliable
  integration/tests/cook/test_basic.py
Labels: flaky-test, internal-green, test

#1340 log stacktraces when executor is asked to kill task
  executor/cook/_version.py
  executor/cook/executor.py
  executor/cook/util.py
Labels: internal-green

#1328 Adds custom timeout to test_preemption_basic
  integration/tests/cook/test_multi_user.py
  integration/tests/cook/util.py
Labels: internal-green, test

#1335 Move other python:3.5 docker image references to python:3.5.9-stretch
  executor/bin/check-version.sh
  integration/bin/run-integration.sh
  scheduler/bin/submit-docker.sh
Labels: internal-green

#1333 Makes test_instance_stats_success more reliable
  integration/tests/cook/test_multi_user.py
Labels: flaky-test, internal-green, test

#1334 Some more tweaks to de-layer docker image
  scheduler/Dockerfile
Labels: internal-green

#1337 Tweak dockerignore for integration tests + scheduler
  integration/.dockerignore
  scheduler/.dockerignore
Labels: internal-green

#1336 Make composite mesos+k8s edn for docker+gke
  scheduler/config-composite.edn
Labels: internal-green

#1341 Makes test_rate_limit_while_creating_job more reliable
  integration/tests/cook/test_multi_user.py
Labels: flaky-test, internal-green, test

#1314 Adds mapping for Failed pod phase
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/controller.clj
Labels: internal-green, k8s

#1338 Makes container defaults be compute-cluster specific
  scheduler/config-k8s.edn
  scheduler/config.edn
  scheduler/src/cook/compute_cluster.clj
  scheduler/src/cook/config.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/mesos/mesos_compute_cluster.clj
  scheduler/src/cook/mesos/task.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/test/cook/test/mesos/task.clj
  scheduler/test/cook/test/zz_simulator.clj
Labels: internal-green, k8s

#1332 Avoids Cook executor when launching on k8s
  integration/tests/cook/util.py
  scheduler/src/cook/compute_cluster.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/mesos/mesos_compute_cluster.clj
  scheduler/src/cook/mesos/task.clj
  scheduler/test/cook/test/mesos/task.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: executor, internal-green, k8s

#1343 Marks one test xfail, makes another more reliable
  integration/tests/cook/test_basic.py
Labels: flaky-test, internal-green, test

#1345 Makes test_unique_host_constraint more reliable
  integration/tests/cook/test_basic.py
Labels: flaky-test, internal-green, test

#1342 Introduces pool-mover plugin
  integration/tests/cook/test_basic.py
  integration/tests/cook/test_multi_user.py
  integration/tests/cook/util.py
  scheduler/src/cook/plugins/adjustment.clj
  scheduler/src/cook/plugins/definitions.clj
  scheduler/src/cook/plugins/demo_plugin.clj
  scheduler/src/cook/plugins/pool_mover.clj
  scheduler/src/cook/rest/api.clj
  scheduler/test/cook/test/rest/api.clj
Labels: internal-green, k8s, pools

#1346 Lowers resource requests for test_instance_stats_success
  integration/tests/cook/test_multi_user.py
Labels: flaky-test, internal-green, test

#1349 Removes :type keys from state maps
  scheduler/src/cook/kubernetes/compute_cluster.clj
Labels: internal-green, k8s

#1351 Outgoing/better gitignore
  executor/.gitignore
Labels: internal-green

#1350 Make reconciler only reconcile mesos tasks.
  integration/travis/run_integration.sh
  scheduler/datomic/data/seed_running_jobs.clj
  scheduler/src/cook/mesos/mesos_compute_cluster.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: internal-green
