Repository twosigma/Cook, pull requests merged in 2019-10, with the labels that each got.

#1222 Adds logging and other test improvements
  integration/.gitignore
  integration/requirements.txt
  integration/setup.cfg
  integration/tests/cook/test_basic.py
  integration/tests/cook/test_cli.py
  integration/tests/cook/test_multi_user.py
  integration/tests/cook/test_pools.py
  integration/tests/cook/util.py
Labels: flaky-test, internal-green, pools, test

#1221 Improvements to k8s volumes
  integration/tests/cook/test_basic.py
  scheduler/config-k8s.edn
  scheduler/src/cook/config.clj
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green

#1226 Check for RW mode in test_default_container_volumes
  integration/tests/cook/test_basic.py
Labels: internal-green

#1228 Periodically reset kerberos auth token
  executor/setup.py
  integration/tests/cook/util.py
Labels: internal-green

#1227 Add docker parameter validation
  integration/tests/cook/test_basic.py
  scheduler/config-k8s.edn
  scheduler/config.edn
  scheduler/src/cook/config.clj
  scheduler/src/cook/rest/api.clj
  scheduler/test/cook/test/rest/api.clj
Labels: internal-green

#1231 Mark test_cook_instance_num xfail
  integration/tests/cook/test_basic.py
Labels: flaky-test, internal-green

#1232 Logs whether or not rate limiting is enforced
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green

#1233 Fix test_docker_fields
  integration/tests/cook/test_basic.py
Labels: internal-green

#1223 Removes 2 builds from travis run
  .travis.yml
  integration/setup.cfg
  integration/tests/conftest.py
  integration/tests/cook/test_cli.py
Labels: internal-green, performance, test

#1230 increase max priority to 16,000,000
  cli/cook/subcommands/submit.py
  integration/tests/cook/test_basic.py
  integration/tests/cook/test_cli.py
  scheduler/src/cook/rest/api.clj
Labels: internal-green

#1237 Pool support
  integration/tests/cook/test_basic.py
  integration/tests/cook/test_pools.py
  integration/tests/cook/util.py
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
Labels: internal-green

#1236 Better logging messages for integration test user changing.
  integration/tests/cook/util.py
Labels: internal-green

#1234 Configure a GKE kubernetes cluster on GKE for running tests.
  scheduler/bin/make-gke-test-cluster
  scheduler/docs/make-kubernetes-namespace.json
Labels: internal-green

#1239 Add max-ports to task constraints
  integration/tests/cook/test_basic.py
  scheduler/src/cook/config.clj
  scheduler/src/cook/rest/api.clj
  scheduler/test/cook/test/rest/api.clj
Labels: internal-green

#1240 Marks test_tail_default_path as xfail
  integration/tests/cook/test_cli.py
Labels: cli, flaky-test, test

#1238 Supports disallowing certain pools for integration tests
  integration/tests/cook/test_cli.py
  integration/tests/cook/util.py
Labels: internal-green, pools, test

#1229 Add support for user, workdir, and env docker parameters
  integration/tests/cook/test_basic.py
  integration/tests/cook/test_multi_user.py
  integration/travis/run_integration.sh
  scheduler/config-k8s.edn
  scheduler/src/cook/config.clj
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/rest/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
Labels: internal-green

#1242 Makes test_list_jobs_by_pool more reliable
  integration/tests/cook/test_basic.py
Labels: flaky-test, internal-green, pools, test

#1246 Makes test_basic_docker_job more reliable
  integration/tests/cook/test_basic.py
Labels: flaky-test, internal-green, test

#1248 Adds pod name and namespace to submit error log
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green, k8s

#1243 Refactor rebalancer to not use global compute cluster
  scheduler/src/cook/mesos.clj
  scheduler/src/cook/rebalancer.clj
  scheduler/src/cook/task.clj
Labels: internal-green

#1244 Refactor handle-resource-offers to not use global compute-cluster
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: internal-green

#1252 Refactor fenzo initialization to not use global compute cluster.
  scheduler/src/cook/mesos.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/test/cook/test/mesos/mesos_compute_cluster.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: internal-green

#1250 Makes environment variable test more reliable
  integration/tests/cook/test_basic.py
Labels: flaky-test, internal-green, test

#1253 Makes test_cancel_instance more reliable
  integration/tests/cook/test_basic.py
Labels: flaky-test, internal-green, test

#1256 Marks test_cat_large_file_no_newlines as xfail
  integration/tests/cook/test_cli.py
Labels: cli, flaky-test, test

#1255 Improves capacity and consumption logs
  scheduler/src/cook/kubernetes/compute_cluster.clj
Labels: internal-green, k8s

#1260 Fix Kubernetes Node Watch
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green

#1259 Refactor cancelled task killer to remove global compute-cluster
  scheduler/src/cook/compute_cluster.clj
  scheduler/src/cook/mesos.clj
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green

#1258 Add a comment
  scheduler/src/cook/mesos.clj
Labels: internal-green

#1262 Logs the zookeeper connection string, leader path
  scheduler/src/cook/components.clj
  scheduler/src/cook/mesos.clj
Labels: internal-green

#1264 Adds leader URL to /info
  integration/tests/cook/test_basic.py
  scheduler/src/cook/rest/api.clj
Labels: internal-green

#1261 Removes 'mesos' from leadership logs
  scheduler/src/cook/mesos.clj
Labels: internal-green

#1266 Marks `test_tail_zero_byte_file` as `xfail`
  integration/tests/cook/test_cli.py
Labels: cli, flaky-test, test

#1263 Makes two tests resilient to "Agent removed"
  integration/tests/cook/test_basic.py
Labels: flaky-test, internal-green, test

#1257 Refactor lingering tasks killer to not use global compute cluster
  scheduler/src/cook/mesos.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: internal-green

#1251 Refactor straggler handler to not use global compute cluster
  scheduler/src/cook/mesos.clj
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green

#1271 Fixes bug in declining offers
  scheduler/src/cook/mesos/mesos_compute_cluster.clj
Labels: bug, internal-green

#1273 Makes test_balanced_host_constraint_can_place more reliable
  integration/tests/cook/test_basic.py
Labels: flaky-test, internal-green, test

#1272 Makes test_instance_stats_running more reliable
  integration/tests/cook/test_multi_user.py
Labels: flaky-test, internal-green, test

#1269 Makes test_group_change_retries more reliable
  integration/tests/cook/test_basic.py
Labels: flaky-test, internal-green, test

#1284 Bug fix: We want to restart the k8s node watch even on a clean exit.
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green

#1280 Better logging about startup/initializing.
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/mesos/mesos_compute_cluster.clj
Labels: internal-green

#1285 Fixes test_instance_stats_running
  integration/tests/cook/test_multi_user.py
Labels: internal-green, test

#1282 Indicate when we're processing a given change.
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
Labels: internal-green

#1279 Report when we detect a pod as deleted
  scheduler/src/cook/kubernetes/controller.clj
Labels: internal-green

#1277 Add a type annotation to make things more clear.
  scheduler/src/cook/kubernetes/controller.clj
Labels: internal-green

#1275 Improve logging as we filter jobs from being considered.
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green

#1274 More logging on nodes being filtered
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
Labels: internal-green
