Repository twosigma/Cook, pull requests merged in 2020-03, with the labels that each got.

#1448 Adds k8s metrics
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/src/cook/kubernetes/metrics.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/kubernetes/controller.clj
Labels: internal-green

#1454 Makes test_show_progress_message_custom_progress_file more reliable
  integration/tests/cook/test_cli.py
Labels: flaky-test, internal-green, test

#1452 Disables test_output_url for k8s runs
  integration/tests/cook/test_basic.py
  integration/tests/cook/test_multi_user.py
Labels: flaky-test, internal-green, k8s, test

#1455 Makes negative retries remaining easier to troubleshoot
  scheduler/src/cook/rest/api.clj
Labels: bug

#1459 Removes expensive log from handle-resource-offers!
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green, performance

#1458 Make test_instance_stats_running more reliable
  integration/tests/cook/test_multi_user.py
Labels: internal-green

#1462 Limit time window of test_list_jobs_by_name queries
  integration/tests/cook/test_basic.py
Labels: internal-green

#1461 Assert success response code in list_jobs test helper
  integration/tests/cook/util.py
Labels: internal-green

#1404 Refactor fileserver into sidecar with progress reporting
  .gitignore
  integration/tests/cook/util.py
  scheduler/config-k8s.edn
  scheduler/src/cook/config.clj
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/mesos/task.clj
  scheduler/src/cook/task.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/mesos/task.clj
  scheduler/test/cook/test/task.clj
  sidecar/.gitignore
  sidecar/Dockerfile
  sidecar/README.md
  sidecar/cook/sidecar/__main__.py
  sidecar/cook/sidecar/config.py
  sidecar/cook/sidecar/exit_sentinel.py
  sidecar/cook/sidecar/file_server.py
  sidecar/cook/sidecar/progress.py
  sidecar/cook/sidecar/tracker.py
  sidecar/cook/sidecar/util.py
  sidecar/cook/sidecar/version.py
  sidecar/setup.py
Labels: internal-green

#1456 Add SSL verification between k8s at cook
  scheduler/src/cook/kubernetes/compute_cluster.clj
Labels: internal-green

#1466 Adds fast fail for Unschedulable pods
  scheduler/docs/reason-code
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/src/cook/schema.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/controller.clj
Labels: internal-green, k8s

#1464 Autoscales based on pending jobs instead of match failures
  scheduler/src/cook/compute_cluster.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: internal-green, k8s

#1463 Changes node label from cook_pool to cook-pool
  scheduler/bin/help-make-cluster
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green, k8s

#1470 Adds exception handling to scan-tasks and launch-tasks
  scheduler/src/cook/kubernetes/compute_cluster.clj
Labels: internal-green, k8s

#1465 Allows synthetic pod namespace to be user's namespace
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
Labels: internal-green, k8s

#1471 Add COOK_SANDBOX, deprecate COOK_WORKDIR for sidecar
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green

#1467 Rename metrics to be consistent with prior metric naming
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/kubernetes/metrics.clj
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green

#1468 add tty support
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green

#1476 Allows pods to briefly be Unschedulable without failing
  scheduler/src/cook/config.clj
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/controller.clj
Labels: internal-green, k8s

#1478 Makes test_user_total_usage more reliable
  integration/tests/cook/test_multi_user.py
Labels: flaky-test, internal-green, test

#1477 Adds synthetic pod anti-affinity to previous hosts
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/scheduler/constraints.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/scheduler/constraints.clj
Labels: internal-green, k8s

#1479 Improves test-job->previous-hosts-to-avoid
  scheduler/test/cook/test/scheduler/constraints.clj
Labels: internal-green, test

#1472 Separate k8s job pods' workdir and sandbox
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green

#1481 add mesos sandbox mount
  integration/tests/cook/test_basic.py
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green

#1483 Adds node anti-affinity for node blocklist labels
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
Labels: bug, internal-green, k8s

#1484 support cs cli commands on kubernetes
  cli/cook/querying.py
  cli/cook/subcommands/cat.py
  cli/cook/subcommands/ls.py
  cli/cook/subcommands/ssh.py
  cli/cook/subcommands/tail.py
Labels: internal-green

#1488 Remove sandbox workaround in test_workdir_volume_overlap
  integration/tests/cook/test_basic.py
Labels: internal-green

#1487 Capture stdout/stderr by default on K8s
  integration/tests/cook/util.py
  scheduler/config-k8s.edn
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: bug, internal-green, test

#1473 cs ssh to $HOME in k8s job pods
  cli/cook/subcommands/ssh.py
  cli/cook/version.py
Labels: internal-green

#1475 add writable scratch space separate from the sandbox
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green

#1493 Makes synthetic pod anti-affinity use AND across requirements
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
Labels: bug, internal-green, k8s, k8s-synthetic-pods
