Repository twosigma/Cook, pull requests merged in 2020-11, with the labels that each got.

#1724 Increases default and max :controller-lock-num-shards
  scheduler/src/cook/config.clj
Labels: internal-green, k8s, performance

#1725 Fixes test-config-settings
  scheduler/test/cook/test/config.clj
Labels: internal-green, k8s, test

#1709 Add API for Disk Limits
  integration/tests/cook/test_basic.py
  scheduler/config-k8s.edn
  scheduler/src/cook/config.clj
  scheduler/src/cook/queries.clj
  scheduler/src/cook/rest/api.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/schema.clj
  scheduler/src/cook/tools.clj
  scheduler/test/cook/test/config.clj
  scheduler/test/cook/test/rest/api.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: disk, internal-green, k8s

#1726 Make the kill-lock be a ReentrantReadWriteLock and add metrics.
  scheduler/src/cook/compute_cluster.clj
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green

#1730 Refactor to make pool taint / label and context configurable
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
Labels: internal-green

#1727 Fix memory leak in k8s state for deleted pods
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/test/cook/test/kubernetes/controller.clj
Labels: internal-green

#1731 Add support for disk field in Java job client
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/Disk.java
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/Job.java
  jobclient/java/src/test/java/com/twosigma/cook/jobclient/JobTest.java
Labels: internal-green

#1728 add metadata env vars
  integration/tests/cook/test_basic.py
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green

#1733 add workload fields to job client
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/Application.java
  jobclient/java/src/test/java/com/twosigma/cook/jobclient/JobClientTest.java
  jobclient/java/src/test/java/com/twosigma/cook/jobclient/JobTest.java
Labels: internal-green

#1729 add support for modifying pod image when checkpointing
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/src/cook/rest/api.clj
  scheduler/src/cook/tools.clj
  scheduler/src/cook/util.clj
Labels: internal-green

#1736 Fixes Java jobclient path in Vagrantfile
  Vagrantfile
Labels: internal-green, jobclient-java

#1738 Add Comment
  scheduler/src/cook/util.clj
Labels: internal-green

#1734 Add disk fields for cs show
  cli/cook/subcommands/show.py
  integration/tests/cook/test_cli.py
  scheduler/config-k8s.edn
Labels: internal-green

#1732 Add support for disk in Python job client
  jobclient/python/cookclient/__init__.py
  jobclient/python/cookclient/jobs.py
  jobclient/python/tests/test_job.py
Labels: internal-green

#1740 Add support for ignoring a taint prefix.
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
Labels: internal-green

#1739 Do not schedule nodes with unschedulable node-spec
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green

#1741 Increase limit for launch-task-num-threads
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
Labels: internal-green

#1743 Make progress an absolute path in k8s
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green

#1747 Add resource request and limit to init-container in pod
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green

#1749 Add ability to parse single Job, update Job -> Builder
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/Job.java
  jobclient/java/src/test/java/com/twosigma/cook/jobclient/JobTest.java
Labels: internal-green
