Repository twosigma/Cook, pull requests merged in 2020-02, with the labels that each got.

#1401 Changes 'dropped item from tx-report-mult' log to INFO
  scheduler/src/cook/datomic.clj
Labels: internal-green

#1402 Adds test and logging for default pool
  integration/tests/cook/test_basic.py
  integration/tests/cook/util.py
  scheduler/config-k8s.edn
  scheduler/src/cook/config.clj
  scheduler/src/cook/tools.clj
Labels: bug, internal-green, k8s, pools, test

#1399 Add support to blacklist nodes in kubernetes that have certain labels
  scheduler/config-k8s.edn
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
Labels: internal-green

#1395 Fix a race where we don't kill a pod thats been sent to kubernetes because the watch hasn't returned yet.
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/test/cook/test/kubernetes/controller.clj
Labels: internal-green

#1397 Makes test_progress_update_submit more reliable
  integration/tests/cook/test_basic.py
Labels: flaky-test, internal-green, test

#1409 Fix nil default pool
  scheduler/config-k8s.edn
  scheduler/src/cook/config.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green

#1407 Suppress errors deleting already deleted pods
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green

#1406 Fix overlapping k8s mounts
  integration/tests/cook/test_basic.py
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green

#1412 Comments failing assertion in test_docker_fields
  integration/tests/cook/test_basic.py
Labels: flaky-test, test

#1414 Upgrade org.clojure/core.cache to 0.8.2
  scheduler/project.clj
Labels: internal-green

#1403 Simplify progress reporting integration test logic
  integration/tests/cook/test_basic.py
  integration/tests/cook/util.py
Labels: internal-green

#1419 Rename fileserver to more generic cook.sidecar
  integration/tests/cook/test_basic.py
  scheduler/config-k8s.edn
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/controller.clj
  sidecar/.dockerignore
  sidecar/.gitignore
  sidecar/Dockerfile
  sidecar/README.md
  sidecar/cook/__init__.py
  sidecar/cook/sidecar/__init__.py
  sidecar/cook/sidecar/__main__.py
  sidecar/cook/sidecar/file_server.py
  sidecar/cook/sidecar/version.py
  sidecar/setup.py
Labels: internal-green

#1416 Avoid NPE when a running job goes completely missing
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/test/cook/test/kubernetes/controller.clj
Labels: internal-green

#1413 Makes test_set_retries_to_attempts_conflict more reliable
  integration/tests/cook/test_basic.py
Labels: flaky-test, internal-green, test

#1421 Adds logging around node and pod watches
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green, k8s

#1368 logs absolute path of the tracked progress file
  executor/cook/executor.py
Labels: internal-green

#1422 Retry k8s startup forever
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
Labels: internal-green

#1420 Added new integration test for kubernetes volume=workdir mount successfully launches.
  integration/tests/cook/test_basic.py
Labels: internal-green

#1423 Fast fail when we get a bad request response from k8s
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green

#1424 Initializes pool->fenzo atom earlier
  scheduler/src/cook/kubernetes/compute_cluster.clj
Labels: bug, internal-green, k8s

#1425 Uses 'Normal exit' reason for successful k8s instances
  scheduler/docs/reason-code
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/src/cook/mesos/reason.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/schema.clj
  scheduler/test/cook/test/kubernetes/controller.clj
Labels: internal-green, k8s

#1426 Decrease default integration test job size.
  integration/tests/cook/test_basic.py
  integration/tests/cook/util.py
Labels: internal-green

#1430 Makes test_max_runtime_exceeded more reliable
  integration/tests/cook/test_basic.py
Labels: flaky-test, test

#1418 don't resolve the sandbox directory when ssh'ing kubernetes
  cli/cook/querying.py
  cli/cook/subcommands/ssh.py
  integration/tests/cook/test_cli.py
Labels: internal-green

#1428 Fixes result reporting for failed xfail tests
  integration/tests/conftest.py
Labels: internal-green, metrics, test

#1427 Name test jobs with their caller function to better identify them.
  integration/tests/cook/test_basic.py
  integration/tests/cook/util.py
Labels: internal-green

#1434 Makes test_configurable_progress_update_submit more reliable
  integration/tests/cook/test_basic.py
Labels: flaky-test, internal-green, test

#1436 Changes 'Failed to get mesos agent state' log from ERROR to INFO
  scheduler/src/cook/mesos/sandbox.clj
Labels: internal-green

#1435 Gate the port-related tests to actually having ports enabled.
  integration/tests/cook/test_basic.py
Labels: internal-green

#1432 Fixes timeout for test_straggler_handling
  integration/tests/cook/test_basic.py
Labels: flaky-test, internal-green, test

#1433 Makes test_set_retries_to_attempts_conflict more reliable
  integration/tests/cook/test_basic.py
Labels: flaky-test, internal-green, test

#1439 Improves log in handle-status-update
  scheduler/src/cook/mesos/mesos_compute_cluster.clj
Labels: internal-green

#1441 Makes test_multiple_rapid_progress_updates_submit more reliable
  integration/tests/cook/test_basic.py
Labels: flaky-test, internal-green, test

#1437 Adds mapping for REASON_TASK_KILLED_DURING_LAUNCH
  integration/tests/cook/test_cli.py
  scheduler/docs/reason-code
  scheduler/src/cook/mesos/mesos_compute_cluster.clj
  scheduler/src/cook/schema.clj
  scheduler/test/cook/test/mesos/mesos_compute_cluster.clj
  scheduler/test/cook/test/rest/api.clj
Labels: internal-green

#1440 don't fail test when init script is used
  integration/tests/cook/test_basic.py
Labels: internal-green

#1296 Sends synthetic pods to k8s to trigger GKE scale-up
  scheduler/config-k8s.edn
  scheduler/src/cook/compute_cluster.clj
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/src/cook/mesos/mesos_compute_cluster.clj
  scheduler/src/cook/monitor.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: internal-green, k8s

#1415 Deflake test_progress_update_rest
  integration/tests/cook/test_basic.py
  integration/tests/cook/util.py
  scheduler/src/cook/progress.clj
Labels: internal-green

#1438 Adds running reason for k8s instances
  scheduler/docs/reason-code
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/src/cook/schema.clj
  scheduler/test/cook/test/kubernetes/controller.clj
  scheduler/test/cook/test/rest/api.clj
Labels: internal-green, k8s

#1442 Change the log line for blocklist to log the key and value.
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green

#1444 Avoid NPE in sandbox calculation when compute cluster is not found.
  scheduler/src/cook/compute_cluster.clj
  scheduler/src/cook/rest/api.clj
  scheduler/test/cook/test/rest/api.clj
Labels: internal-green

#1443 Fix integration test that attempts to submit a bad job with no image.
  integration/tests/cook/test_basic.py
  integration/tests/cook/util.py
Labels: internal-green

#1450 Make progress tests more reliable
  integration/tests/cook/test_basic.py
Labels: internal-green

#1445 Makes test_instance_stats_success more reliable
  integration/tests/cook/test_multi_user.py
Labels: flaky-test, internal-green, test

#1446 Makes test_submit_with_command_prefix more reliable
  integration/tests/cook/test_cli.py
Labels: cli, flaky-test, internal-green, test

#1451 Makes test_group_kill_simple more reliable
  integration/tests/cook/reasons.py
  integration/tests/cook/test_basic.py
Labels: flaky-test, internal-green, test

#1447 Improves synthetic pods
  integration/tests/cook/util.py
  scheduler/bin/help-make-cluster
  scheduler/bin/make-gke-test-clusters
  scheduler/bin/priority-class-cook-workload.yaml
  scheduler/bin/priority-class-synthetic-pod.yaml
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
Labels: internal-green, k8s
