Repository twosigma/Cook, pull requests merged in 2020-04, with the labels that each got.

#1494 CLI: fix broken unit tests and warnings
  .travis.yml
  cli/cook/dateparser.py
  cli/cook/http.py
  cli/pytest.ini
  cli/setup.py
  cli/tests/subcommands/test_dateparser.py
  cli/tests/subcommands/test_querying.py
  cli/travis/setup.sh
Labels: internal-green

#1495 Remove dependency on docker apt to build Cook image
  scheduler/Dockerfile
Labels: internal-green

#1491 Make config changes more lightweight and not need lein uberjar
  scheduler/Dockerfile
Labels: internal-green

#1496 Make k8s sidecar readiness probe optional
  scheduler/config-k8s.edn
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/controller.clj
Labels: internal-green

#1497 Require dateutil v2.8.1 for CLI tests
  cli/setup.py
  cli/travis/setup.sh
  integration/requirements.txt
Labels: internal-green

#1489 Marks pods with un-initialized containers as failed
  integration/tests/cook/reasons.py
  integration/tests/cook/test_basic.py
  integration/tests/cook/util.py
  scheduler/docs/reason-code
  scheduler/src/cook/config.clj
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/src/cook/schema.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/controller.clj
Labels: internal-green, k8s, k8s-fast-fail

#1502 Make cli integration adapters module configurable
  integration/tests/cook/cli.py
Labels: internal-green

#1490 Add checkpoint field
  integration/tests/cook/test_basic.py
  scheduler/docs/scheduler-rest-api.adoc
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/rest/api.clj
  scheduler/src/cook/schema.clj
  scheduler/src/cook/tools.clj
  scheduler/test/cook/test/rest/api.clj
Labels: internal-green

#1499 Processes each pod only once on pod watch initialization
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green, k8s, performance

#1505 Sets min-nodes to 0 when creating test GKE clusters
  scheduler/bin/help-make-cluster
Labels: internal-green, k8s, test

#1501 Removes blocklisted node anti-affinity
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
Labels: bug, internal-green, k8s, k8s-synthetic-pods

#1508 Gracefully handles missing pod in k8s task scanning
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/test/cook/test/kubernetes/controller.clj
Labels: bug, internal-green, k8s

#1504 set main container envs on init container
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green

#1510 change checkpointing volume from init container to scratch space
  integration/tests/cook/test_basic.py
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green

#1511 Refactor CLI to support plugin overrides from wrapper
  cli/README.md
  cli/cook/__main__.py
  cli/cook/cli.py
  cli/cook/configuration.py
  cli/cook/http.py
  cli/cook/plugins.py
  cli/tests/subcommands/test_querying.py
  integration/tests/cook/cli.py
  integration/tests/cook/test_cli.py
  integration/tests/cook/util.py
Labels: internal-green

#1516 Improve integration test behavior when run single-process
  integration/tests/cook/conftest.py
  integration/tests/cook/util.py
Labels: internal-green

#1517 Mark flaky test_output_url as xfail
  integration/tests/cook/test_basic.py
Labels: internal-green

#1513 Don't connect to kubernetes on finished instance
  cli/cook/mesos.py
  cli/cook/subcommands/cat.py
  cli/cook/subcommands/ls.py
  cli/cook/subcommands/tail.py
Labels: internal-green

#1512 Pass through job info to cs commands
  cli/cook/querying.py
  cli/cook/subcommands/cat.py
  cli/cook/subcommands/ls.py
  cli/cook/subcommands/ssh.py
  cli/cook/subcommands/tail.py
Labels: internal-green

#1519 CLI release 3.0.0
  cli/cook/version.py
Labels: internal-green

#1520 Change default check time for cs wait to 15 seconds.
  cli/cook/subcommands/wait.py
Labels: internal-green

#1521 Make it so that we can see who is rate limited in our HTTP log.
  scheduler/src/cook/components.clj
Labels: internal-green

#1524 Improves k8s autoscaling metrics
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green, k8s, metrics

#1515 Allows removing cpu limit in k8s
  scheduler/src/cook/config.clj
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green, k8s, performance

#1522 Change output of errors from cs submit from stdout to stderr
  cli/cook/subcommands/submit.py
  integration/tests/cook/cli.py
  integration/tests/cook/test_cli.py
Labels: internal-green

#1469 Adds MESOS_DIRECTORY to the k8s environment
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green, k8s

#1492 Support for specifying the default container on a per-pool basis
  integration/tests/cook/test_basic.py
  integration/tests/cook/util.py
  scheduler/config-composite.edn
  scheduler/config-k8s.edn
  scheduler/src/cook/config.clj
  scheduler/src/cook/rest/api.clj
  scheduler/test/cook/test/rest/api.clj
Labels: internal-green

#1527 Avoids synthetic pods in handle-pod-preemption
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/test/cook/test/kubernetes/controller.clj
Labels: internal-green, k8s, k8s-synthetic-pods

#1514 Use google metadata server
  scheduler/src/cook/kubernetes/compute_cluster.clj
Labels: internal-green

#1526 Adds lock-sharding to k8s controller
  scheduler/src/cook/config.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/test/cook/test/config.clj
  scheduler/test/cook/test/kubernetes/controller.clj
  scheduler/test/cook/test/rest/api.clj
Labels: internal-green, k8s, performance

#1523 Add memory-overhead to checkpointing config
  integration/tests/cook/test_basic.py
  scheduler/src/cook/compute_cluster.clj
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/mesos/mesos_compute_cluster.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: internal-green, k8s

#1530 add flag to use google service account
  scheduler/config-composite.edn
  scheduler/config-k8s.edn
  scheduler/src/cook/kubernetes/compute_cluster.clj
Labels: internal-green

#1529 Launches k8s tasks in parallel
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
Labels: internal-green, k8s, performance
