Repository twosigma/Cook, pull requests merged in 2020-05, with the labels that each got.

#1518 Handle Killed by user reason code
  integration/tests/cook/reasons.py
  integration/tests/cook/test_basic.py
  scheduler/docs/reason-code
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/schema.clj
Labels: internal-green

#1537 Avoids NPE when pod metadata is nil
  scheduler/src/cook/kubernetes/api.clj
Labels: bug, internal-green, k8s

#1538 Logs pod events
  scheduler/java/com/twosigma/cook/kubernetes/WatchHelper.java
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/kubernetes/controller.clj
Labels: internal-green, k8s

#1536 Sends matches to launch-tasks in bulk
  scheduler/src/cook/compute_cluster.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/mesos/mesos_compute_cluster.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: internal-green, k8s, performance

#1541 Adds safe-to-evict annotation to synthetic pods
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
Labels: internal-green, k8s, k8s-synthetic-pods

#1539 Don't checkpoint when max attempts exceeded
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green

#1546 Avoids future for Mesos launch-tasks! call
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green

#1540 Check for preemption using preemption pod label
  scheduler/docs/reason-code
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/src/cook/schema.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/controller.clj
Labels: internal-green

#1550 Skips test_mesos_containerizer_image_support
  integration/tests/cook/test_basic.py
  integration/tests/cook/test_cli.py
Labels: internal-green, test

#1548 Skips match when there are no considerable jobs
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/test/testutil.clj
Labels: internal-green, metrics, performance

#1552 log pod metadata
  scheduler/src/cook/kubernetes/controller.clj
Labels: internal-green

#1554 re-enbable test_kubernetes_checkpointing
  integration/tests/cook/test_basic.py
Labels: internal-green

#1551 Automates GKE dev environment setup
  .gitignore
  README.md
  Vagrantfile
  scheduler/bin/bootstrap
  scheduler/bin/help-delete-temporary-clusters
  scheduler/bin/help-make-cluster
  scheduler/bin/make-gke-test-clusters
  scheduler/bin/run-local-kubernetes.sh
  scheduler/config-k8s.edn
Labels: internal-green, k8s

#1555 Upgrades k8s client library to 7.0.0
  scheduler/java/com/twosigma/cook/kubernetes/WatchHelper.java
  scheduler/project.clj
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/kubernetes/controller.clj
Labels: internal-green, k8s

#1560 don't set cpu limit on sidecar if not setting on main container
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green

#1562 Supports running the CLI integration tests against k8s
  integration/tests/cook/cli.py
  integration/tests/cook/test_cli.py
Labels: cli, internal-green, pools, test

#1563 Makes vagrant python bootstrapping not run as root
  Vagrantfile
  scheduler/bin/bootstrap
Labels: internal-green, test

#1561 Do not use :missing state for preempted pod.
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/controller.clj
Labels: internal-green

#1556 Deletes unused cook.curator code
  scheduler/src/cook/components.clj
  scheduler/src/cook/curator.clj
  scheduler/test/cook/test/mesos.clj
Labels: internal-green

#1565 Makes test_basic_submit more reliable
  integration/tests/cook/test_basic.py
Labels: flaky-test, internal-green, test

#1553 Adds lru_cache to util.settings
  integration/tests/cook/util.py
Labels: internal-green, performance, test

#1568 update checkpointing settings
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green
