Repository twosigma/Cook, pull requests merged in 2020-06, with the labels that each got.

#1558 Adds impersonation to query requests
  jobclient/src/main/java/com/twosigma/cook/jobclient/JobClient.java
Labels: internal-green, jobclient-java

#1557 Adds reason string to Instance in jobclient
  jobclient/src/main/java/com/twosigma/cook/jobclient/Instance.java
Labels: internal-green, jobclient-java

#1574 add support for init container checkpointing mounts
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green

#1573 Fix an O(n**2) calculation in computing k8s offers.
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
Labels: internal-green

#1569 Python Client API
  .gitignore
  .travis.yml
  README.md
  integration/tests/cook/test_client.py
  jobclient/java/pom.xml
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/Application.java
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/Executor.java
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/FetchableURI.java
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/Group.java
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/GroupListener.java
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/HostPlacement.java
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/Instance.java
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/InstanceDecorator.java
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/Job.java
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/JobClient.java
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/JobClientException.java
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/JobClientInterface.java
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/JobListener.java
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/StragglerHandling.java
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/auth/spnego/BasicSPNegoSchemeFactory.java
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/auth/spnego/GSSCredentialProvider.java
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/constraint/Constraint.java
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/constraint/Constraints.java
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/constraint/OneToOneConstraint.java
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/constraint/Operator.java
  jobclient/java/src/test/java/com/twosigma/ConstraintTest.java
  jobclient/java/src/test/java/com/twosigma/cook/jobclient/FetchableURITest.java
  jobclient/java/src/test/java/com/twosigma/cook/jobclient/GroupTest.java
  jobclient/java/src/test/java/com/twosigma/cook/jobclient/InstanceTest.java
  jobclient/java/src/test/java/com/twosigma/cook/jobclient/JobClientTest.java
  jobclient/java/src/test/java/com/twosigma/cook/jobclient/JobTest.java
  jobclient/python/README.md
  jobclient/python/cookclient/__init__.py
  jobclient/python/cookclient/instance.py
  jobclient/python/cookclient/jobs.py
  jobclient/python/cookclient/util.py
  jobclient/python/docs/Makefile
  jobclient/python/docs/make.bat
  jobclient/python/docs/source/api.rst
  jobclient/python/docs/source/conf.py
  jobclient/python/docs/source/index.rst
  jobclient/python/docs/source/usage.rst
  jobclient/python/setup.py
  jobclient/python/tests/test_instance.py
  jobclient/python/tests/test_job.py
Labels: internal-green

#1576 Rename package from cookclient to cook-client-api
  jobclient/python/setup.py
Labels: internal-green

#1577 Dask on Cook Design Proposal
  dask/docs/design.md
Labels: internal-green

#1579 Update Python client to 0.2.0
  .gitignore
  integration/tests/cook/test_client.py
  jobclient/python/cookclient/__init__.py
  jobclient/python/cookclient/containers.py
  jobclient/python/cookclient/instance.py
  jobclient/python/cookclient/jobs.py
  jobclient/python/cookclient/util.py
  jobclient/python/docs/source/api.rst
  jobclient/python/docs/source/index.rst
  jobclient/python/docs/source/usage.rst
  jobclient/python/tests/test_instance.py
  jobclient/python/tests/test_job.py
Labels: internal-green

#1583 Fixes whitespace bug in .travis.yml
  .travis.yml
  scheduler/travis/setup.sh
Labels: internal-green

#1585 Make separate matching chime per pool
  integration/tests/cook/test_multi_user.py
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green

#1588 Adds links to README
  README.md
Labels: documentation, internal-green

#1589 Removes json annotation from groups.md
  scheduler/docs/groups.md
Labels: documentation, internal-green

#1581 Fix several O(#pods * #nodes) and O(#pools) bugs in k8s code.
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/src/cook/tools.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/kubernetes/controller.clj
  scheduler/test/cook/test/tools.clj
Labels: internal-green
