Repository twosigma/Cook, pull requests merged in 2020-07, with the labels that each got.

#1590 Refactor out common method for matching regexps against a pool name.
  scheduler/src/cook/rest/api.clj
  scheduler/src/cook/tools.clj
  scheduler/test/cook/test/tools.clj
Labels: internal-green

#1593 add kill instance test helper method
  integration/tests/cook/util.py
Labels: internal-green

#1594 Adds port mappings support to k8s pod spec and python client
  integration/tests/cook/test_client.py
  jobclient/python/cookclient/__init__.py
  jobclient/python/cookclient/containers.py
  jobclient/python/cookclient/jobs.py
  jobclient/python/tests/test_job.py
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green

#1586 Avoids autoscaling beyond what users have quota to run
  scheduler/src/cook/rest/api.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/tools.clj
Labels: bug, internal-green, k8s, k8s-synthetic-pods

#1595 Implement a total number of nodes and pods quota for k8s.
  scheduler/config-composite.edn
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
Labels: internal-green

#1582 Enhanced offer generation and updated GPU constraint
  integration/tests/cook/test_basic.py
  integration/tests/cook/test_cli.py
  scheduler/config-k8s.edn
  scheduler/src/cook/config.clj
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/pool.clj
  scheduler/src/cook/rest/api.clj
  scheduler/src/cook/scheduler/constraints.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/src/cook/tools.clj
  scheduler/test/cook/test/config.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/pool.clj
  scheduler/test/cook/test/rest/api.clj
  scheduler/test/cook/test/scheduler/constraints.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: internal-green

#1605 Fix NPE when we ask a k8s pool for offers when it has none
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
Labels: internal-green

#1602 match pools in round-robin order
  scheduler/src/cook/config.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/mesos.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/mesos/mesos_mock.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
  scheduler/test/cook/test/zz_simulator.clj
Labels: internal-green

#1606 Fix "unable to get node from node name XXXX" errors.
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
Labels: internal-green

#1608 skip non-k8s pools in k8s cluster
  scheduler/src/cook/kubernetes/compute_cluster.clj
Labels: internal-green

#1609 Adds seeding Cook pools to the README
  README.md
Labels: internal-green, k8s

#1559 Adds cs admin limits copy
  cli/cook/cli.py
  cli/cook/subcommands/admin.py
  cli/cook/util.py
Labels: cli, internal-green, pools

#1597 Adds GPU job support in kubernetes
  integration/tests/cook/test_client.py
  integration/tests/cook/util.py
  jobclient/python/cookclient/__init__.py
  jobclient/python/docs/source/usage.rst
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/scheduler/constraints.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
Labels: internal-green

#1612 Corrects some problematic language
  scheduler/CHANGELOG.md
Labels: internal-green, problematic-language

#1611 One GPU job per GPU node
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/scheduler/constraints.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/scheduler/constraints.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: internal-green, k8s

#1615 Fix Python job client docs for readthedocs
  jobclient/python/docs/source/conf.py
  jobclient/python/requirements.txt
Labels: documentation, jobclient-python

#1592 Support config-based global quotas for a pool
  integration/tests/cook/test_basic.py
  integration/tests/cook/util.py
  scheduler/bin/help-make-cluster
  scheduler/config-composite.edn
  scheduler/datomic/data/seed_k8s_pools.clj
  scheduler/src/cook/config.clj
  scheduler/src/cook/rest/api.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/tools.clj
  scheduler/test/cook/test/tools.clj
Labels: internal-green

#1614 Forces processing when state scanning in k8s
  scheduler/src/cook/kubernetes/controller.clj
Labels: bug, internal-green, k8s

#1613 Replaces "Slave" with "Agent" in cs show output
  cli/cook/subcommands/show.py
Labels: cli, internal-green, problematic-language

#1580 Java jobclient v0.6.0
  jobclient/java/pom.xml
  scheduler/project.clj
Labels: internal-green, jobclient-java

#1618 One GPU task per VM
  scheduler/src/cook/scheduler/constraints.clj
  scheduler/test/cook/test/scheduler/constraints.clj
Labels: internal-green

#1620 Remove integration test for 2 GPUs
  integration/tests/cook/test_client.py
Labels: internal-green

#1624 Updates CLI version to 3.1.0
  cli/cook/version.py
Labels: cli, internal-green

#1622 Gracefully handles missing resource in total-resource
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
Labels: bug, internal-green, k8s, metrics

#1623 Uses 1024*1024 as the k8s memory multiplier
  integration/tests/cook/test_basic.py
  integration/tests/cook/test_cli.py
  integration/tests/cook/test_client.py
  scheduler/src/cook/kubernetes/api.clj
Labels: bug, internal-green, k8s

#1626 GPU support for the Java jobclient
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/Job.java
  jobclient/java/src/test/java/com/twosigma/cook/jobclient/JobTest.java
Labels: internal-green

#1617 Adds attribution labels to synthetic pods
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
Labels: internal-green, k8s, k8s-synthetic-pods
