Repository twosigma/Cook, pull requests merged in 2020-01, with the labels that each got.

#1353 Makes test_output_url more reliable
  integration/tests/cook/test_basic.py
Labels: flaky-test, internal-green, test

#1347 Fixes bugs in util.wait_for_instance, test_change_failed_retries
  integration/tests/cook/test_basic.py
  integration/tests/cook/util.py
Labels: flaky-test, internal-green, test

#1357 Fixes incorrect rate-limit reason in /unscheduled_jobs
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/unscheduled.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
  scheduler/test/cook/test/unscheduled.clj
Labels: bug, internal-green

#1358 Makes test_mea_culpa_retries more reliable
  integration/tests/cook/test_basic.py
Labels: flaky-test, internal-green, test

#1360 fixes the compute-cluster argument in mesos-scheduler call to receive-offers
  scheduler/src/cook/mesos/mesos_compute_cluster.clj
Labels: internal-green

#1354 Avoids matching onto nodes that have reached their pod limit
  integration/tests/cook/test_basic.py
  integration/tests/cook/util.py
  scheduler/src/cook/compute_cluster.clj
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/mesos/mesos_compute_cluster.clj
  scheduler/src/cook/scheduler/constraints.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
Labels: enhancement, internal-green, k8s

#1363 Correct misnumbered 403 error codes for swagger
  scheduler/src/cook/rest/api.clj
Labels: internal-green

#1364 Remove missing plugin from config.edn
  scheduler/config.edn
Labels: internal-green

#1293 Add logs fileserver
  fileserver/Dockerfile
  fileserver/README.md
  fileserver/cook/__init__.py
  fileserver/cook/__main__.py
  fileserver/cook/file_server.py
  fileserver/cook/version.py
  fileserver/setup.py
  integration/tests/cook/test_basic.py
  scheduler/bin/make-gke-test-clusters
  scheduler/config-k8s.edn
  scheduler/src/cook/compute_cluster.clj
  scheduler/src/cook/config.clj
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/src/cook/mesos/mesos_compute_cluster.clj
  scheduler/src/cook/rest/api.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/schema.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/test/cook/test/scheduler/constraints.clj
  scheduler/test/cook/test/scheduler/fenzo_utils.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: internal-green

#1366 fixes the failing tests after sandbox refactoring
  scheduler/test/cook/test/rest/api.clj
Labels: test

#1371 fix test-task-metadata->pod unit test
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green

#1374 Add minimesos zookeeper flag in run-docker.sh
  cli/.gitignore
  scheduler/bin/run-docker.sh
Labels: internal-green

#1372 disable test that can't run in travis
  integration/tests/cook/test_basic.py
  integration/travis/run_integration.sh
Labels: internal-green

#1359 Review and implement all 30 state pairs in the kubernetes controller.
  scheduler/docs/kubernetes-state.dot
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/kubernetes/controller.clj
Labels: internal-green

#1362 populates the user parameter in docker container parameters
  integration/tests/cook/test_basic.py
  integration/tests/cook/util.py
  scheduler/project.clj
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/rest/api.clj
  scheduler/src/cook/tools.clj
  scheduler/test/cook/test/rest/api.clj
  simulator/resources/job_schedule.edn
  simulator/src/main/cook/sim/runner.clj
  simulator/src/main/cook/sim/schedule.clj
Labels: internal-green

#1375 Logs the compute cluster name instead of entire object in safe-kill-task
  scheduler/src/cook/compute_cluster.clj
Labels: internal-green

#1373 Promote progress-aggregator-chan to components graph
  scheduler/src/cook/components.clj
  scheduler/src/cook/mesos/mesos_compute_cluster.clj
  scheduler/src/cook/progress.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/test/cook/test/zz_simulator.clj
Labels: internal-green

#1365 ssh cli support for kubernetes
  cli/cook/querying.py
  cli/cook/subcommands/cat.py
  cli/cook/subcommands/ls.py
  cli/cook/subcommands/ssh.py
  cli/cook/subcommands/tail.py
Labels: internal-green

#1381 Makes test_multi_user_usage more reliable
  integration/tests/cook/test_multi_user.py
  integration/tests/cook/util.py
Labels: flaky-test, internal-green, test

#1382 Improves logging for 'weird' k8s states
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/test/cook/test/kubernetes/controller.clj
Labels: internal-green, k8s

#1383 Improves logging in write-status-to-datomic
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green

#1384 Makes pod-watch exception log INFO level
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green, k8s

#1385 Updates changelog and version for v1.38.1
  scheduler/CHANGELOG.md
  scheduler/project.clj
Labels: internal-green

#1388 Fix warnings from pytest
  integration/setup.cfg
  integration/tests/cook/test_basic.py
Labels: internal-green, test

#1377 Add REST endpoint for posting job progress updates
  integration/tests/cook/test_basic.py
  integration/tests/cook/util.py
  scheduler/src/cook/components.clj
  scheduler/src/cook/mesos/mesos_compute_cluster.clj
  scheduler/src/cook/progress.clj
  scheduler/src/cook/rest/api.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/test/cook/test/rest/api.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: internal-green

#1390 Various small tweaks to the state machine
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/test/cook/test/kubernetes/controller.clj
Labels: internal-green

#1393 Use scalar-requests for job container resources
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green

#1391 Adds timeout to test metrics POST request
  integration/tests/conftest.py
Labels: internal-green, metrics, test

#1396 Makes log in logging-exception-handler be INFO level
  scheduler/src/cook/rest/api.clj
Labels: internal-green

#1392 Handles pod submission failures
  integration/tests/cook/test_basic.py
  scheduler/docs/kubernetes-state.dot
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/kubernetes/controller.clj
Labels: internal-green, k8s

#1400 Skips two multi-user usage tests for k8s only
  integration/tests/cook/test_multi_user.py
Labels: test
