Repository twosigma/Cook, pull requests merged in 2020-12, with the labels that each got.

#1753 Allow disk request/limit to be an int
  integration/tests/cook/test_basic.py
  scheduler/src/cook/rest/api.clj
  scheduler/test/cook/test/rest/api.clj
Labels: internal-green

#1756 Refactor authenticator initialization
  scheduler/src/cook/kubernetes/compute_cluster.clj
Labels: internal-green

#1750 Migration to GitHub Actions from Travis CI
  .github/workflows/executor-tests.yml
  .github/workflows/integration-tests.yml
  .github/workflows/simulator-tests.yml
  .github/workflows/unit-tests.yml
  .travis.yml
  README.md
  executor/travis/setup.sh
  integration/tests/cook/util.py
  integration/travis/prepare_integration.sh
  integration/travis/run_integration.sh
  scheduler/travis/setup.sh
  simulator/travis/run_simulation.sh
  travis/build_cook_executor.sh
  travis/install_mesos.sh
  travis/prepare.sh
  travis/show_executor_logs.sh
  travis/show_scheduler_logs.sh
  travis/start_scheduler.sh
  travis/upload_logs.sh
Labels: internal-green

#1754 Specify that disk request and limit are in MiB
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/Disk.java
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/Job.java
Labels: internal-green

#1752 Add ability to convert JSON->Builder, set fields when JSONizing
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/Job.java
  jobclient/java/src/test/java/com/twosigma/cook/jobclient/JobTest.java
Labels: internal-green, jobclient-java

#1751 Updates java jobclient to v0.8.1
  jobclient/java/pom.xml
  scheduler/project.clj
Labels: internal-green, jobclient-java

#1761 Use add over set when parsing JSON.
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/Job.java
  jobclient/java/src/test/java/com/twosigma/cook/jobclient/JobTest.java
Labels: internal-green

#1765 Adds location to compute cluster
  scheduler/src/cook/compute_cluster.clj
  scheduler/src/cook/schema.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/test/cook/test/compute_cluster.clj
Labels: internal-green

#1763 Makes k8s API client read timeout configurable
  scheduler/src/cook/kubernetes/compute_cluster.clj
Labels: internal-green

#1746 Scheduling and running disk jobs
  scheduler/config-k8s.edn
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/src/cook/scheduler/constraints.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/scheduler/constraints.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: internal-green

#1766 Sends synthetic pod to same location as previous checkpoint
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: internal-green, k8s, k8s-synthetic-pods

#1759 Set special authenticator refresh logic needed for non-GKE K8s
  scheduler/java/com/twosigma/cook/kubernetes/TokenRefreshingAuthenticator.java
  scheduler/src/cook/kubernetes/compute_cluster.clj
Labels: internal-green

#1760 Updates java jobclient version to 0.8.2
  jobclient/java/pom.xml
  scheduler/project.clj
Labels: internal-green, jobclient-java

#1719 Logs largest job, offer by resource
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green, logging
