Repository twosigma/Cook, pull requests merged in 2020-08, with the labels that each got.

#1629 Adds compute-cluster-type and url to test metrics
  integration/tests/conftest.py
Labels: internal-green, metrics, test

#1627 Adds agent_id as preferred alternative to slave_id
  integration/tests/cook/test_basic.py
  scheduler/src/cook/rest/api.clj
  scheduler/test/cook/test/rest/api.clj
Labels: internal-green, problematic-language

#1630 Adds the calling test name to the User-Agent on kill_jobs
  integration/tests/cook/util.py
Labels: internal-green, test

#1631 Allow explicit `None` in JobClient.submit_all
  integration/tests/cook/test_client.py
  jobclient/python/cookclient/__init__.py
  jobclient/python/cookclient/util.py
Labels: internal-green, jobclient-python

#1632 Makes "killing cancelled task" log be INFO
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green

#1628 handle preemption on pod initialization
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/test/cook/test/kubernetes/controller.clj
Labels: internal-green

#1621 Runs only one pool in test_list_jobs_by_pool
  integration/tests/cook/test_basic.py
Labels: internal-green, performance, test

#1636 Allows prefixed job labels to become k8s pod labels
  scheduler/config-k8s.edn
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/rest/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
  scheduler/test/cook/test/rest/api.clj
Labels: internal-green, k8s

#1642 Logs at start and end of job ranking
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green

#1643 Improves per-user launch-rate-limit logging
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green

#1644 Improves matching log
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: internal-green

#1640 Adds /shutdown-leader API endpoint
  scheduler/src/cook/rest/api.clj
  scheduler/test/cook/test/rest/api.clj
Labels: internal-green

#1646 New API for reading kubectl file
  scheduler/src/cook/kubernetes/compute_cluster.clj
Labels: internal-green

#1645 Un-lazy list of hosts a job has run on as a perf optimization
  scheduler/src/cook/scheduler/constraints.clj
Labels: internal-green

#1634 Reverse order of quota application
  scheduler/src/cook/tools.clj
  scheduler/test/cook/test/tools.clj
Labels: internal-green

#1649 De-lazy the list of constraints to avoid locking in Fenzo.
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green

#1633 Adds cs admin instances
  cli/cook/subcommands/admin.py
  cli/cook/subcommands/jobs.py
  cli/cook/util.py
Labels: cli, internal-green

#1607 Adds support for EQUALS constraints in k8s
  scheduler/bin/help-make-cluster
  scheduler/config-k8s.edn
  scheduler/src/cook/config.clj
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/scheduler/constraints.clj
  scheduler/test/cook/test/scheduler/constraints.clj
Labels: constraints, internal-green, k8s
