Repository twosigma/Cook, pull requests merged in 2020-09, with the labels that each got.

#1639 Dynamic cluster configuration
  cli/cook/querying.py
  integration/tests/cook/test_basic.py
  integration/tests/cook/test_multi_user.py
  integration/tests/cook/util.py
  scheduler/config-composite.edn
  scheduler/config-k8s.edn
  scheduler/src/cook/components.clj
  scheduler/src/cook/compute_cluster.clj
  scheduler/src/cook/config.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/mesos.clj
  scheduler/src/cook/mesos/mesos_compute_cluster.clj
  scheduler/src/cook/rest/api.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/schema.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/src/cook/tools.clj
  scheduler/src/cook/util.clj
  scheduler/test/cook/test/compute_cluster.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/mesos.clj
  scheduler/test/cook/test/rest/api.clj
  scheduler/test/cook/test/util.clj
  simulator/travis/scheduler_config.edn
Labels: internal-green

#1657 Updates CLI version to 3.2.0
  cli/cook/version.py
Labels: internal-green

#1656 Fix dynamic cluster integration tests
  integration/tests/cook/test_basic.py
Labels: internal-green

#1658 Fix StopIteration bug
  cli/cook/querying.py
Labels: internal-green

#1659 Updates CLI version to 3.3.0
  cli/cook/version.py
Labels: internal-green

#1662 Fix errors when using dynamic clusters
  scheduler/src/cook/compute_cluster.clj
  scheduler/src/cook/rest/api.clj
  scheduler/src/cook/task.clj
  scheduler/test/cook/test/compute_cluster.clj
  scheduler/test/cook/test/rest/api.clj
Labels: internal-green

#1660 Adds information to the launching tasks log
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green

#1663 Improves logging when we stop launching synthetic pods
  scheduler/src/cook/kubernetes/compute_cluster.clj
Labels: internal-green

#1664 Adds information to the matching offers log
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green

#1666 Deletes unschedulable synthetic pods
  integration/tests/cook/test_basic.py
  scheduler/src/cook/config.clj
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: bug, internal-green, k8s, k8s-synthetic-pods

#1667 Logs offer and job percentiles
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/task_stats.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: internal-green

#1668 Adds helper methods for constraints and GPU model
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/Job.java
  jobclient/java/src/test/java/com/twosigma/cook/jobclient/JobTest.java
Labels: constraints, internal-green, jobclient-java

#1669 Java jobclient v0.7.0
  jobclient/java/pom.xml
  scheduler/project.clj
Labels: internal-green

#1672 Correctly parses jobs with no gpus
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/Job.java
  jobclient/java/src/test/java/com/twosigma/cook/jobclient/JobTest.java
Labels: bug, internal-green, jobclient-java

#1673 Java jobclient v0.7.1
  jobclient/java/pom.xml
  scheduler/project.clj
Labels: internal-green, jobclient-java

#1670 Refactor ratelimit code
  scheduler/src/cook/rate_limit.clj
  scheduler/src/cook/rate_limit/generic.clj
  scheduler/src/cook/rate_limit/token_bucket_filter.clj
  scheduler/src/cook/unscheduled.clj
  scheduler/test/cook/test/rate_limit/generic.clj
  scheduler/test/cook/test/unscheduled.clj
Labels: internal-green

#1671 Refactor regexp list matching code.
  scheduler/src/cook/tools.clj
Labels: internal-green

#1674 Reduces excessive logging
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/tools.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
  scheduler/test/cook/test/tools.clj
Labels: internal-green

#1677 fix missing cluster check
  scheduler/src/cook/mesos.clj
  scheduler/test/cook/test/mesos.clj
Labels: internal-green

#1679 Add rate limits per compute cluster.
  .travis.yml
  integration/tests/cook/test_multi_user.py
  integration/travis/run_integration_ratelimit.sh
  integration/travis/scheduler_travis_config.edn
  scheduler/bin/help-make-cluster
  scheduler/config-composite.edn
  scheduler/config-k8s.edn
  scheduler/config.edn
  scheduler/src/cook/compute_cluster.clj
  scheduler/src/cook/config.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/mesos/mesos_compute_cluster.clj
  scheduler/src/cook/rate_limit.clj
  scheduler/src/cook/rate_limit/generic.clj
  scheduler/src/cook/regexp_tools.clj
  scheduler/src/cook/scheduler/constraints.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/src/cook/tools.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/regexp_tools.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
  scheduler/test/cook/test/tools.clj
  scheduler/test/cook/test/zz_simulator.clj
Labels: internal-green

#1684 Optimize GPU constraint
  scheduler/src/cook/scheduler/constraints.clj
Labels: internal-green

#1685 Optimize user-defined-constraint
  scheduler/src/cook/scheduler/constraints.clj
  scheduler/test/cook/test/scheduler/constraints.clj
Labels: internal-green

#1680 Fix dynamic cluster integration tests
  Vagrantfile
  integration/tests/cook/test_basic.py
  integration/tests/cook/test_dynamic_clusters.py
  integration/tests/cook/test_multi_user.py
  integration/tests/cook/util.py
  scheduler/config-k8s.edn
  scheduler/src/cook/compute_cluster.clj
Labels: internal-green

#1691 Remove metatransaction.core import that causes problem with mount.
  scheduler/src/cook/components.clj
  scheduler/src/cook/quota.clj
Labels: internal-green

#1689 Remove circular dependency by moving a query out of cook.tools
  scheduler/src/cook/queries.clj
  scheduler/src/cook/quota.clj
  scheduler/src/cook/rest/api.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/scheduler/share.clj
Labels: internal-green

#1690 Refactor to propagate pool-name into quota filters.
  scheduler/src/cook/rest/api.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/tools.clj
  scheduler/test/cook/test/tools.clj
Labels: internal-green

#1688 Add the ability to flush a rate-limit from the cache
  scheduler/src/cook/rate_limit.clj
  scheduler/src/cook/rate_limit/generic.clj
  scheduler/test/cook/test/rate_limit/generic.clj
Labels: internal-green
