Repository twosigma/Cook, pull requests merged in 2020-10, with the labels that each got.

#1681 Adds optional command to cs ssh
  cli/cook/subcommands/ssh.py
  cli/cook/version.py
Labels: cli, enhancement, internal-green

#1687 Warns when jobs are unmatched for too long
  scheduler/src/cook/config.clj
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green

#1694 Refactor special redirect to code to support POST and DELETE
  integration/tests/cook/util.py
Labels: internal-green

#1695 fix dynamic cluster integration test
  integration/tests/cook/test_dynamic_clusters.py
Labels: internal-green

#1698 Change log from ERROR to WARN
  scheduler/src/cook/compute_cluster.clj
Labels: internal-green

#1697 We need an actual UID for test_docker_port_mapping to run.
  integration/tests/cook/test_basic.py
Labels: internal-green

#1699 Fix compute-cluster API tests when run in docker.
  scheduler/bin/run-docker.sh
Labels: internal-green

#1696 Adds different rate limit for auth-bypass requests
  scheduler/config-k8s.edn
  scheduler/src/cook/config.clj
Labels: bug, internal-green, k8s, progress-reporting

#1700 Lowers default auth-bypass request rate limit
  scheduler/src/cook/config.clj
  scheduler/test/cook/test/config.clj
Labels: internal-green

#1701 add checkpointing kill switch
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green

#1692 Per-user per-pool job launch rate limit
  integration/tests/cook/cli.py
  integration/tests/cook/test_multi_user.py
  integration/tests/cook/util.py
  integration/travis/run_integration_ratelimit.sh
  scheduler/config.edn
  scheduler/src/cook/components.clj
  scheduler/src/cook/config.clj
  scheduler/src/cook/pool.clj
  scheduler/src/cook/quota.clj
  scheduler/src/cook/rate_limit.clj
  scheduler/src/cook/rate_limit/generic.clj
  scheduler/src/cook/rest/api.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/schema.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/src/cook/tools.clj
  scheduler/src/cook/unscheduled.clj
  scheduler/test/cook/test/quota.clj
  scheduler/test/cook/test/rest/api.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
  scheduler/test/cook/test/tools.clj
  scheduler/test/cook/test/unscheduled.clj
Labels: internal-green

#1703 add checkpointing options
  cli/cook/subcommands/show.py
  cli/cook/subcommands/submit.py
  cli/cook/version.py
Labels: internal-green

#1704 Enable tracking of how rate limiting is affecting the queue.
  scheduler/src/cook/rest/api.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/tools.clj
  scheduler/test/cook/test/tools.clj
Labels: internal-green

#1706 Make our cache sizes configurable from the configuration file.
  scheduler/src/cook/caches.clj
  scheduler/src/cook/components.clj
  scheduler/src/cook/config.clj
  scheduler/src/cook/plugins/launch.clj
  scheduler/src/cook/plugins/submission.clj
  scheduler/src/cook/scheduler/data_locality.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/src/cook/tools.clj
  scheduler/test/cook/test/rest/api.clj
  scheduler/test/cook/test/scheduler/constraints.clj
  scheduler/test/cook/test/scheduler/data_locality.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: internal-green

#1710 Shortens the 'writing tasks' log
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green, logging

#1711 Shortens the 'updating dynamic clusters' log
  integration/tests/cook/test_cli.py
  scheduler/src/cook/compute_cluster.clj
Labels: internal-green, logging

#1715 Removes group name validation from Java client
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/Group.java
  jobclient/java/src/test/java/com/twosigma/cook/jobclient/GroupTest.java
Labels: bug, internal-green, jobclient-java

#1721 Shortens the 'launching matched tasks' log
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green, logging

#1720 Shortens the 'Will not checkpoint' log
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green, logging

#1713 Adds per-user queue length limits
  integration/tests/cook/test_multi_user.py
  integration/tests/cook/util.py
  scheduler/config-k8s.edn
  scheduler/src/cook/cached_queries.clj
  scheduler/src/cook/components.clj
  scheduler/src/cook/config.clj
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/mesos.clj
  scheduler/src/cook/mesos/heartbeat.clj
  scheduler/src/cook/mesos/mesos_compute_cluster.clj
  scheduler/src/cook/mesos/mesos_mock.clj
  scheduler/src/cook/mesos/sandbox.clj
  scheduler/src/cook/monitor.clj
  scheduler/src/cook/plugins/pool_mover.clj
  scheduler/src/cook/queries.clj
  scheduler/src/cook/queue_limit.clj
  scheduler/src/cook/rebalancer.clj
  scheduler/src/cook/regexp_tools.clj
  scheduler/src/cook/rest/api.clj
  scheduler/src/cook/scheduler/constraints.clj
  scheduler/src/cook/scheduler/data_locality.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/tools.clj
  scheduler/src/cook/util.clj
  scheduler/test/cook/test/benchmark.clj
  scheduler/test/cook/test/mesos/mesos_mock.clj
  scheduler/test/cook/test/monitor.clj
  scheduler/test/cook/test/queue_limit.clj
  scheduler/test/cook/test/rebalancer.clj
  scheduler/test/cook/test/regexp_tools.clj
  scheduler/test/cook/test/rest/api.clj
  scheduler/test/cook/test/tools.clj
Labels: internal-green

#1723 Gracefully handles unknown job resource type
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/tools.clj
Labels: internal-green
