Repository twosigma/Cook, pull requests merged in 2021-03, with the labels that each got.

#1799 Numerous autoscaling improvements
  scheduler/src/cook/caches.clj
  scheduler/src/cook/config.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: internal-green

#1793 Add memory limit job label
  integration/tests/cook/test_basic.py
  integration/tests/cook/util.py
  scheduler/config-k8s.edn
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green

#1802 Stop calculating offer attribute map unnecessarily then throw it away.
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green

#1805 fix cook memory label handling
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green

#1804 Fixes cs memory formatting
  cli/cook/format.py
  cli/cook/subcommands/usage.py
Labels: bug, cli, internal-green

#1806 Ignores the space used by synthetic pods
  scheduler/config-k8s.edn
  scheduler/src/cook/config.clj
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green

#1808 Allows synthetic pods to have a non-default termination grace period
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green, k8s, k8s-synthetic-pods, performance

#1811 Support for disable_mea_culpa_retries on python jobclient.submit
  jobclient/python/cookclient/__init__.py
Labels: internal-green, jobclient-python

#1813 Add support for node tenuring taint
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green

#1815 fix memory request value sent to pod
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green

#1814 Upgrade cook-client-api-version to 0.3.2
  jobclient/python/cookclient/__init__.py
Labels: internal-green

#1817 Update cook-client-api version to 0.3.3
  jobclient/python/cookclient/__init__.py
Labels: internal-green

#1819 Supports synthetic pod inter-pod anti-affinity
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green, k8s, k8s-synthetic-pods

#1820 Improves several integration tests
  integration/tests/cook/test_cli.py
Labels: internal-green, python, test

#1822 Add constraints to jobspec.submit, bump version
  jobclient/python/cookclient/__init__.py
Labels: internal-green

#1826 Gracefully handles nil watch objects
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green, k8s

#1827 Allows namespace to be added to synthetic pod anti-affinity
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green, k8s, k8s-synthetic-pods

#1825 Gracefully handles nodes with no pods in get-consumption
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
Labels: internal-green, k8s

#1829 Makes test_memory_limit more reliable
  integration/tests/cook/test_basic.py
Labels: internal-green

#1830 Logs watch response status field
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green, k8s, logging

#1831 Treats prolonged ContainersNotReady condition as failure
  scheduler/docs/reason-code
  scheduler/src/cook/config.clj
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/src/cook/schema.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green, k8s, k8s-fast-fail

#1835 Separate lock shards per compute cluster.
  scheduler/src/cook/config.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/test/cook/test/kubernetes/compute_cluster.clj
  scheduler/test/cook/test/kubernetes/controller.clj
Labels: internal-green

#1834 Optimize novel-host-constraint
  scheduler/src/cook/scheduler/constraints.clj
Labels: internal-green

#1837 Prevents inactive pools from having a scheduling loop
  scheduler/src/cook/pool.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: internal-green
