Repository twosigma/Cook, pull requests merged in 2021-01, with the labels that each got.

#1775 Deletes get_kubernetes_nodes from integration tests
  integration/tests/cook/test_basic.py
  integration/tests/cook/test_pools.py
  integration/tests/cook/util.py
Labels: internal-green, test

#1767 Add disk fields to cs submit
  cli/cook/subcommands/submit.py
  integration/tests/cook/test_cli.py
Labels: internal-green

#1770 Adds checkpoint locality constraint
  integration/tests/cook/test_dynamic_clusters.py
  integration/tests/cook/util.py
  scheduler/src/cook/compute_cluster.clj
  scheduler/src/cook/scheduler/constraints.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: constraints, internal-green, k8s

#1771 Refactor cs kubernetes commands
  cli/cook/querying.py
  cli/cook/subcommands/cat.py
  cli/cook/subcommands/ls.py
  cli/cook/subcommands/ssh.py
  cli/cook/subcommands/tail.py
  cli/cook/version.py
Labels: internal-green

#1772 Do not add resource limit for mem
  integration/tests/cook/test_basic.py
  scheduler/config-k8s.edn
  scheduler/src/cook/config.clj
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green

#1776 Fix NPE bug for sidecar mem limit
  scheduler/config-k8s.edn
Labels: internal-green

#1779 Support longer pod names
  scheduler/java/com/twosigma/cook/kubernetes/WatchHelper.java
  scheduler/project.clj
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green

#1782 Upgrade version of cli client 3.7.0 in preparation for release.
  cli/cook/version.py
Labels: internal-green

#1781 Allows getting /usage for all users
  scheduler/src/cook/rest/api.clj
Labels: internal-green

#1778 Validates job resources by node type
  integration/tests/cook/test_basic.py
  scheduler/src/cook/config.clj
  scheduler/src/cook/plugins/definitions.clj
  scheduler/src/cook/plugins/demo_plugin.clj
  scheduler/src/cook/plugins/submission.clj
  scheduler/src/cook/rest/api.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/test/cook/test/jobclient/jobclient.clj
  scheduler/test/cook/test/plugins/submission.clj
  scheduler/test/cook/test/rest/api.clj
Labels: internal-green

#1783 Makes job->acceptable-compute-clusters configurable
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: internal-green
