Repository twosigma/Cook, pull requests merged in 2021-02, with the labels that each got.

#1786 Logs exceptions in deep-merge-with
  scheduler/src/cook/util.clj
  scheduler/test/cook/test/util.clj
Labels: internal-green

#1789 Removes integration and simulator tests from GitHub
  .github/workflows/integration-tests.yml
  .github/workflows/simulator-tests.yml
Labels: internal-green

#1787 Enable local k8s
  integration/tests/cook/test_basic.py
  integration/tests/cook/util.py
  scheduler/src/cook/config.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/src/cook/tools.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green

#1791 Takes only top X jobs when triggering autoscaling
  scheduler/src/cook/config.clj
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green, k8s, k8s-synthetic-pods, performance

#1790 extend plugin infrastructure to support new subcommands
  cli/README.md
  cli/cook/cli.py
  cli/cook/plugins.py
  integration/tests/cook/test_cli_subcommand_plugin.py
Labels: internal-green

#1794 Updates CLI version to 3.8.0
  cli/cook/version.py
Labels: internal-green

#1795 cook: pass decorator through to List<Job> parseFromJSON
  jobclient/java/src/main/java/com/twosigma/cook/jobclient/Job.java
  jobclient/java/src/test/java/com/twosigma/cook/jobclient/JobTest.java
Labels: internal-green

#1797 Marks reason correctly for pod failures from preemption
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/test/cook/test/kubernetes/controller.clj
Labels: internal-green, k8s

#1796 Cli constraints
  cli/cook/subcommands/submit.py
  cli/cook/version.py
  integration/tests/cook/test_cli.py
Labels: internal-green

#1788 Supports a default k8s pool
  scheduler/src/cook/kubernetes/api.clj
Labels: internal-green
