Repository twosigma/Cook, pull requests merged in 2021-04, with the labels that each got.

#1840 Do fenzo unassign in batches outside of the fenzo lock
  scheduler/config-k8s.edn
  scheduler/src/cook/compute_cluster.clj
  scheduler/src/cook/kubernetes/compute_cluster.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/src/cook/mesos.clj
  scheduler/src/cook/mesos/mesos_compute_cluster.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/test/testutil.clj
  scheduler/src/cook/util.clj
  scheduler/test/cook/test/compute_cluster.clj
  scheduler/test/cook/test/mesos/mesos_compute_cluster.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
  scheduler/test/cook/test/util.clj
Labels: internal-green

#1842 Make the lock vector a vector, not a sequence.
  scheduler/src/cook/kubernetes/compute_cluster.clj
Labels: internal-green

#1841 Split metrics for synthetic pods and normal pods for time until run and time until waiting
  scheduler/src/cook/kubernetes/controller.clj
Labels: internal-green

#1845 Fix time-until-waiting metric.
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/test/cook/test/kubernetes/controller.clj
Labels: internal-green

#1843 Improves cs ssh messages for k8s jobs
  cli/cook/subcommands/ssh.py
Labels: internal-green

#1848 Bumps CLI version to v3.9.1
  cli/cook/version.py
Labels: cli, internal-green

#1847 Adds pod label prefix to workload labels
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green, k8s

#1849 Adds pod labels for application name and version
  scheduler/src/cook/kubernetes/api.clj
  scheduler/test/cook/test/kubernetes/api.clj
Labels: internal-green, k8s

#1852 make straggler kill mea culpa
  scheduler/src/cook/schema.clj
Labels: internal-green

#1857 Updates java jobclient version to 0.8.5
  jobclient/java/pom.xml
  scheduler/project.clj
Labels: internal-green

#1854 Adds field for how long the job queued before each instance
  scheduler/src/cook/rest/api.clj
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/src/cook/schema.clj
Labels: internal-green

#1860 Conj the smaller set into the bigger set in update-host-reservation
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: internal-green

#1859 Optimize TaskRequestAdapter.
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green

#1861 Refactor VirtualMachineLeaseAdaptor to go through factory.
  scheduler/src/cook/scheduler/scheduler.clj
  scheduler/test/cook/test/scheduler/constraints.clj
  scheduler/test/cook/test/scheduler/scheduler.clj
Labels: internal-green

#1862 Skips inactive pools when ranking
  scheduler/src/cook/scheduler/scheduler.clj
Labels: internal-green

#1864 Introduces :pod/deleting state
  scheduler/docs/kubernetes-state.dot
  scheduler/src/cook/kubernetes/api.clj
  scheduler/src/cook/kubernetes/controller.clj
  scheduler/test/cook/test/kubernetes/controller.clj
Labels: internal-green
